#!/bin/bash
export PATH=/usr/local/bin/:/usr/bin:/bin:$PATH
CUR_PATH=`pwd`
basepath=$(cd `dirname $0`; pwd)
echo $CUR_PATH
echo $basepath

if [[ $1 = cdata ]]; then
    
    if [[ $2 ]]; then
        #statements
        cd $basepath/conventWithXmlAndTxt
        ./cdata ../datalablImg $2
        cd $basepath/darknet
        ./dktrain cdata
    else
        cd $basepath/conventWithXmlAndTxt
        ./cdata ../datalablImg PNG
        cd $basepath/darknet
        ./dktrain cdata
    fi
elif [[ $1 = fclass ]]; then
    #statements
    cd $basepath/conventWithXmlAndTxt
    ./fclass ../datalablImg $2 $3
elif [[ $1 = train ]]; then
    #statements
    echo "training with datalablImg data"
    cd $basepath/darknet
    ./dktrain train $2 $3
elif [[ $1 = test ]]; then
    #statements
    echo "run test"
    cd $2
    $2/darknet detector test $basepath/darknet/cfg/my.data  $basepath/darknet/cfg/yolov3_test.cfg $3 $4
elif [[ $1 = retrain ]]; then
    echo "continue training with datalablImg data"
    cd $basepath/darknet
    ./dktrain retrain $2 $3
    
else
    echo "create data with cmd:"
    echo "dktool cdata"
    echo "start train with cmd:"
    echo "dktool train darknetexePath darknetConvFilePath"
    echo "test traindata with cmd:"
    echo "dktool test  darknetexePath darketTrainWeightsPath imagePath"
fi