#!/bin/bash
export PATH=/usr/local/bin/:/usr/bin:/bin:$PATH
CUR_PATH=`pwd`
basepath=$(cd `dirname $0`; pwd)
echo $CUR_PATH
echo $basepath

if [[ $1 = cdata ]]; then
    #statements
    cd $basepath
    python3 createTrainAndTest.py
elif [[ $1 = retrain ]]; then
	#statements
	cd $basepath
	echo "darknet path:"${2}
    echo "darknet trainxxx_weights_file:"${3}
    echo "continue train..."
    $2 detector train $basepath/cfg/my.data $basepath/cfg/yolov3-tiny.cfg $3  2>&1 | tee log/train_yolov3.log

elif [[ $1 = train ]]; then
    #statements
    cd $basepath
    echo "darknet path:"${2}
    echo "darknet trainxxx_weights_file:"${3}
    echo "continue train..."
    $2 detector train $basepath/cfg/my.data $basepath/cfg/yolov3-tiny.cfg $3  2>&1 | tee log/train_yolov3.log

else
    echo "dktrain darknetexePath darknetConvFilePath"
fi